name: shop_k
description: A new Flutter application.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
   sdk: ">=2.10.4 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.0+1
  flutter_card_swipper: ^0.4.0
  dio: ^4.0.6
  shared_preferences: ^2.0.17
  rounded_loading_button: ^2.1.0
  cupertino_icons: ^1.0.5
  badges: ^3.0.2
  geolocator: ^9.0.2
  google_maps_flutter: ^2.2.3
  provider: ^6.0.5
  firebase_core: ^2.5.0
  firebase_auth: ^4.2.6
  image_picker: ^0.8.6+1
  new_version: ^0.3.1
  flutter_automation: ^2.0.0
  country_code_picker: ^2.0.2
  permission_handler: ^10.2.0
  flutter_rating_bar: ^4.0.1
  simple_star_rating: ^0.0.3
  awesome_dialog: ^3.0.2
  firebase_messaging: ^14.2.2
  url_launcher: ^6.1.9
  flutter_geocoder: ^0.2.2-nullsafety
  sqflite: ^2.2.4+1
  google_place: ^0.4.7
  location: ^4.4.0
  google_geocoding: ^0.2.0
  geocoding: ^2.0.5
  date_time_picker: ^2.1.0
  flutter_localizations:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.11.0

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/logo.png"


flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/
    - assets/languages/en.json
    - assets/languages/id.json

  fonts:
    - family: Tajawal
      fonts:
        - asset: fonts/Tajawal-Regular.ttf
          weight: 700


